Adding terraform template
juanchovelezpro/aik-portal pull request #4
Opened 2020-10-02 18:30 UTC by juanchovelezpro

2020-10-24 17:27 UTC, juanfe2793 requested changes

2020-10-24 17:27 UTC, juanfe2793 commented on Terraform IaC/main.tf
> +  min_size             = 2
Con 1 está bien para empezar

2020-10-24 17:27 UTC, juanfe2793 commented on aik-app-ui/server.js
> +var backendHost = process.env.BACK_HOST || '172.17.0.2' || '172.17.0.3';
Esto va a fallar cuando hagan el apply. La IP cambia.

2020-10-24 17:27 UTC, juanfe2793 commented on Terraform IaC/main.tf
> +  user_data       = <<EOF
En el user data pueden usar:
`
  user_data = file("../scripts/nvm.sh")
`
En el nuevo directorio ponen el script que van a ejecutar. Lo ideal es hacer todo con salt.

2020-10-24 17:27 UTC, juanfe2793 commented on Terraform IaC/main.tf
> + resource "aws_db_instance" "aik-rds" {
agregar:

`
port = 3306
publicly_accessible = false
vpc_security_groups_ids = 
db_subnet_group_name = 
multi_az = false
final_snapshot_identifier = 
`

2020-10-24 17:27 UTC, juanfe2793 commented on Terraform IaC/variables.tf
> +variable "db_password"{
Este tipo de variables, normalmente se ponen en un archivo secrets.tf que se encripta en el repo. 

Por ahora esta bien así.

2020-11-04 02:16 UTC, JuanDoradoP commented on aik-app-ui/server.js
> +var backendHost = process.env.BACK_HOST || '172.17.0.2' || '172.17.0.3';
Profe, eso se tendría que hacer con una variable de entorno cierto?

2020-11-06 00:05 UTC, merged